---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
    
driver_config:
  forward:
  - 80:80

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    attributes:
