---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
    driver_config:
      network:
        forward:
        - 22:2222
        - 80:8080
suites:
  - name: default
    run_list:
      - recipe[apache::default]
    attributes:
