name             'setup'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures setup'
long_description 'Installs/Configures setup'
version          '0.2.0'
